'use strict';

// Read and write the credentials file that qc-check generates.
//
// Two kinds of file exist in the wild:
//   - generated: first line is MARKER, body is `module.exports = <JSON>;`.
//     qc-check owns it and may rewrite it.
//   - hand-written: anything else, for example a file that `require`s a
//     shared secrets module. qc-check reads it (the runtime has to) but never
//     writes it, because a rewrite would silently drop whatever logic it holds.
//
// No function here logs, prints or returns a value in an error message: JSON
// and require errors can quote the offending source line, so every error
// names the path only.

const fs = require('fs');
const path = require('path');

// envVarNames is a pure function of the name; requiring config.js has no side
// effects (its CLI only runs when it is the main module).
const { envVarNames } = require('../runtime/config');

const MARKER = '// Generated by qc-check.';
const HEADER = [
  `${MARKER} Edit with \`qc-check env credentials <env>\`.`,
  '// Gitignored. Never commit this file.',
];

function isPlain(v) {
  return v !== null && typeof v === 'object' && !Array.isArray(v);
}

function firstLine(file) {
  let fd;
  try {
    fd = fs.openSync(file, 'r');
    const buf = Buffer.alloc(256);
    const n = fs.readSync(fd, buf, 0, buf.length, 0);
    return buf.slice(0, n).toString('utf8').split(/\r?\n/)[0];
  } catch (_) {
    return null;
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }
}

// True when qc-check wrote this file and may therefore rewrite it.
function isGenerated(file) {
  const line = firstLine(file);
  return typeof line === 'string' && line.startsWith(MARKER);
}

// A generated file is parsed as data rather than executed, so a stale require
// cache or a tampered body cannot run code here.
function parseGenerated(file) {
  const text = fs.readFileSync(file, 'utf8');
  const m = text.match(/module\.exports\s*=\s*([\s\S]*?);?\s*$/);
  if (!m) throw new Error(`Credentials file ${file} has the qc-check marker but no module.exports.`);
  let data;
  try {
    data = JSON.parse(m[1]);
  } catch (_) {
    throw new Error(`Credentials file ${file} has the qc-check marker but its body is not valid JSON.`);
  }
  if (!isPlain(data)) throw new Error(`Credentials file ${file} must export an object.`);
  return data;
}

// A hand-written file is code by definition, so it is required like the
// runtime does. The cache entry is dropped first: this process may have
// written or read it already.
function requireFresh(file) {
  const abs = path.resolve(file);
  try {
    delete require.cache[require.resolve(abs)];
  } catch (_) {
    /* not cached yet */
  }
  let data;
  try {
    // eslint-disable-next-line global-require
    data = require(abs);
  } catch (_) {
    throw new Error(`Credentials file ${file} could not be loaded (syntax or export error).`);
  }
  if (!isPlain(data)) throw new Error(`Credentials file ${file} must export an object.`);
  return data;
}

// The credentials object, or {} when the file does not exist.
function read(file) {
  if (!fs.existsSync(file)) return {};
  return isGenerated(file) ? parseGenerated(file) : requireFresh(file);
}

class HandWrittenError extends Error {
  constructor(file) {
    const base = path.basename(file);
    super(
      `${file} is hand-written (its first line is not "${MARKER}"), so qc-check will not touch it.\n` +
        `  Either edit it by hand, or move it aside and re-run to get a managed file:\n` +
        `    mv ${base} ${base}.bak && qc-check env credentials <env>`,
    );
    this.code = 'HAND_WRITTEN';
  }
}

function render(data) {
  return `${HEADER.join('\n')}\nmodule.exports = ${JSON.stringify(data, null, 2)};\n`;
}

// Write the whole file in the generated format, mode 0600. The temp file is
// created 0600 from the start and renamed over the target, so a crash leaves
// the old file intact and the secrets are never world-readable, even briefly.
function write(file, data) {
  if (fs.existsSync(file) && !isGenerated(file)) throw new HandWrittenError(file);
  if (!isPlain(data)) throw new Error('credentials data must be an object');
  const dir = path.dirname(path.resolve(file));
  fs.mkdirSync(dir, { recursive: true });
  const tmp = path.join(dir, `.${path.basename(file)}.${process.pid}.${Date.now()}.tmp`);
  let fd;
  try {
    fd = fs.openSync(tmp, 'wx', 0o600);
    fs.writeSync(fd, render(data));
    fs.fsyncSync(fd);
    fs.closeSync(fd);
    fd = undefined;
    // openSync's mode is filtered by umask; set it explicitly.
    fs.chmodSync(tmp, 0o600);
    fs.renameSync(tmp, file);
  } catch (err) {
    if (fd !== undefined) fs.closeSync(fd);
    try {
      fs.unlinkSync(tmp);
    } catch (_) {
      /* already gone */
    }
    throw new Error(`could not write ${file}: ${err.code || 'write failed'}`);
  }
}

// Set one environment's account. A field left undefined (or empty) keeps the
// value already in the file, so "leave the password blank to keep it" never
// needs the caller to hold the old value.
function setEnv(file, env, { username, password } = {}) {
  if (fs.existsSync(file) && !isGenerated(file)) throw new HandWrittenError(file);
  const data = read(file);
  const prev = isPlain(data[env]) ? data[env] : {};
  const next = {
    username: usable(username) ? username : prev.username,
    password: usable(password) ? password : prev.password,
  };
  if (!usable(next.username) || !usable(next.password)) {
    throw new Error(`both a username and a password are required for "${env}"`);
  }
  data[env] = next;
  write(file, data);
}

// True when a block was removed.
function removeEnv(file, env) {
  if (!fs.existsSync(file)) return false;
  if (!isGenerated(file)) throw new HandWrittenError(file);
  const data = read(file);
  if (!(env in data)) return false;
  delete data[env];
  write(file, data);
  return true;
}

// Same rule as runtime/config.js: the template placeholder is not a value.
function usable(v) {
  return typeof v === 'string' && v !== '' && v !== 'CHANGE_ME';
}

// Presence only, the same answers as config.credentialStatus():
// 'env' | 'file' | 'incomplete' | 'missing' | 'unreadable'.
//
// Re-implemented rather than calling config.credentialStatus because that
// one resolves the host from process.cwd(), caches the config per process and
// reads the file through require(), whose cache would still hold the
// pre-write contents after setup or `env credentials` rewrites it. The CLI
// acts on --dir and writes the file mid-process, so it needs a fresh read of
// an explicit path.
function status(file, env) {
  const names = envVarNames(env);
  if (usable(process.env[names.user]) && usable(process.env[names.pass])) return 'env';
  if (!fs.existsSync(file)) return 'missing';
  let data;
  try {
    data = read(file);
  } catch (_) {
    return 'unreadable';
  }
  const block = data[env];
  if (block && usable(block.username) && usable(block.password)) return 'file';
  if (block) return 'incomplete';
  return 'missing';
}

// Whether an environment has a block in the file, and whether it has a
// username. Booleans only, so a caller can offer "Enter keeps the current one"
// without ever holding the value.
function has(file, env) {
  let data = {};
  try {
    data = read(file);
  } catch (_) {
    return { block: false, username: false, password: false };
  }
  const b = isPlain(data[env]) ? data[env] : null;
  return { block: Boolean(b), username: Boolean(b && usable(b.username)), password: Boolean(b && usable(b.password)) };
}

// Credentials exported in the environment for one env, or null.
function fromEnvVars(env) {
  const names = envVarNames(env);
  const username = process.env[names.user];
  const password = process.env[names.pass];
  if (usable(username) && usable(password)) return { username, password };
  return null;
}

// 'absent' | 'generated' | 'hand-written'
function kind(file) {
  if (!fs.existsSync(file)) return 'absent';
  return isGenerated(file) ? 'generated' : 'hand-written';
}

module.exports = {
  MARKER,
  isGenerated,
  read,
  write,
  setEnv,
  removeEnv,
  status,
  has,
  fromEnvVars,
  kind,
  envVarNames,
  HandWrittenError,
};
